CREATE DATABASE IF NOT EXISTS `liligo` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE USER IF NOT EXISTS 'liligo'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON liligo.* TO 'liligo'@'%';
FLUSH PRIVILEGES;
